name: Trigger auto deployment for testsaltawindows

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/testsaltawindows-AutoDeployTrigger-8a425030-332c-4d1e-bd61-3f4b85860969.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: testsalta.azurecr.io
          username: ${{ secrets.TESTSALTAWINDOWS_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTSALTAWINDOWS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: testsalta.azurecr.io/api-accountinfo:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTSALTAWINDOWS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n testsaltawindows -g test13 --server testsalta.azurecr.io --username  ${{ secrets.TESTSALTAWINDOWS_REGISTRY_USERNAME }} --password ${{ secrets.TESTSALTAWINDOWS_REGISTRY_PASSWORD }}
            az containerapp update -n testsaltawindows -g test13 --image testsalta.azurecr.io/api-accountinfo:${{ github.sha }}
